change parent to base-pom
celements/celements-migration pull request #2
Opened 2018-03-09 17:03 UTC by msladek

2018-03-13 16:40 UTC, ebeutler submitted a review, later dismissed

2018-03-14 04:41 UTC, fpichler requested changes

2018-03-14 04:41 UTC, fpichler commented on pom.xml
> +      <artifactId>xwiki-plugin-mailsender</artifactId>
I think the plugins can bei removed for migration manager

2018-03-14 09:13 UTC, fpichler approved these changes

2018-03-14 09:45 UTC, merged